name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller pdfplumber pdfminer.six pillow

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed --name EventParser parse_event_report.py

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: EventParser
          path: dist/EventParser.exe
